import React from "react";
import AcrossCraigleith from "./AcrossCraigleith"
import AlpineExpress from "./AlpineExpress"
import Backbowl from "./Backbowl"
import Backstairs from "./Backstairs"
import BlueBird from "./BlueBird"
import BlueTrail from "./BlueTrail"
import BruceTrail from "./BruceTrail"
import BruceTrailConnection from "./BruceTrailConnection"
import BruceTrailLoop from "./BruceTrailLoop"
import Connector from "./Connector"
import Crossover from "./Crossover"
import DeerRun from "./DeerRun"
import DownwardDog from "./DownwardDog"
import EnchantedForest from "./EnchantedForest"
import FarmRoad from "./FarmRoad"
import FeelingLazy from "./FeelingLazy"
import ForestGump from "./ForestGump"
import ForestLane from "./ForestLane"
import GreenTrail from "./GreenTrail"
import GreenYellowConnector from "./GreenYellowConnector"
import LightBlueTrail from "./LightBlueTrail"
import LoreeForest from "./LoreeForest"
import LoreeLookoutLoop from "./LoreeLookoutLoop"
import LostLoop from "./LostLoop"
import LoversLoop from "./LoversLoop"
import NorthsideTrail from "./NorthsideTrail"
import OrangeTrail from "./OrangeTrail"
import OverTheHill from "./OverTheHill"
import PurpleTrail from "./PurpleTrail"
import R2R from "./R2R"
import RedTrail from "./RedTrail"
import RidgeRun from "./RidgeRun"
import RiverRoute from "./RiverRoute"
import RobinsRun from "./RobinsRun"
import Shortcut from "./Shortcut"
import SouthAscent from "./SouthAscent"
import StusLine from "./StusLine"
import SweetSteeps from "./SweetSteeps"
import TheEastRut from "./TheEastRut"
import TheGlades from "./TheGlades"
import TheSpur from "./TheSpur"
import TheSwitchback from "./TheSwitchback"
import TheWestRut from "./TheWestRut"
import ToBench from "./ToBench"
import ToBruceTrail from "./ToBruceTrail"
import ToCraigleithNorthLodge from "./ToCraigleithNorthLodge"
import ToCrossover from "./ToCrossover"
import ToEastRut from "./ToEastRut"
import ToGreenTrail from "./ToGreenTrail"
import ToLookoutBench from "./ToLookoutBench"
import ToRedTrail from "./ToRedTrail"
import ToRiver from "./ToRiver"
import ToSouth from "./ToSouth"
import ToSteeps from "./ToSteeps"
import ToSweetSteeps from "./ToSweetSteeps"
import ToSwitchback from "./ToSwitchback"
import ToTrailhead from "./ToTrailhead"
import TopTraverse from "./TopTraverse"
import Woodpecker from "./Woodpecker"
import YellowTrail from "./YellowTrail"


const ShowTrail = (props) => {
  return (
    <>
      <AcrossCraigleith longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <AlpineExpress longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <Backbowl longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <Backstairs longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <BlueBird longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <BlueTrail longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <BruceTrail longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <BruceTrailConnection longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <BruceTrailLoop longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <Connector longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <Crossover longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <DeerRun longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <DownwardDog longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <EnchantedForest longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <FarmRoad longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <FeelingLazy longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ForestGump longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ForestLane longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <GreenTrail longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <GreenYellowConnector longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <LightBlueTrail longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <LoreeForest longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <LoreeLookoutLoop longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <LostLoop longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <LoversLoop longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <NorthsideTrail longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <OrangeTrail longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <OverTheHill longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <PurpleTrail longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <R2R longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <RedTrail longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <RidgeRun longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <RiverRoute longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <RobinsRun longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <Shortcut longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <SouthAscent longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <StusLine longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <SweetSteeps longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <TheEastRut longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <TheGlades longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <TheSpur longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <TheSwitchback longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <TheWestRut longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ToBench longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ToBruceTrail longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ToCraigleithNorthLodge longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ToCrossover longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ToEastRut longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ToGreenTrail longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ToLookoutBench longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ToRedTrail longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ToRiver longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ToSouth longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ToSteeps longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ToSweetSteeps longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ToSwitchback longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <ToTrailhead longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <TopTraverse longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <Woodpecker longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
      <YellowTrail longitudeDelta={props.longitudeDelta} markerImages={props.markerImages} trailPattern={props.trailPattern}/>
    </>
  )
}

export default ShowTrail;
